= RHEL installation prerequisites
:last_updated: 3/20/2020
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Prepare the system and ThoughtSpot clusters for installation.

[cols="5,95",frame=none,grid=none]
|===
| &#10063;
| <<set-up-hosts,1.
Set up hosts for the ThoughtSpot cluster>>

| &#10063;
| <<partition-hosts,2.
Partition the hosts>>

| &#10063;
| <<install-rhel,3.
Install RHEL version 7.7 on all hosts>>

| &#10063;
| <<enable-hosts,4.
Enable the hosts to download RHEL packages>>

| &#10063;
| <<enable-ansible,5.
Enable an Ansible Control Server>>

| &#10063;
| <<disable-selinux,6.
Disable SELinux>>
|===

[#set-up-hosts]
== Set up hosts for the ThoughtSpot cluster

Set up hosts for the ThoughtSpot cluster on your chosen platform.
Please refer to the relevant deployment sections in our documentation for the exact specification for the hosts: CPU, memory, and disks.

* ThoughtSpot-certified hardware appliance manufactured by xref:/appliance/hardware/installing-dell.adoc[DELL]
* ThoughtSpot-certified hardware appliance manufactured by xref:/appliance/hardware/installing-the-smc.adoc[SMC]
* xref:/appliance/aws/configuration-options.adoc[Amazon Web Services (AWS) EC2]
* xref:/appliance/gcp/configuration-options.adoc[Google Cloud Platform (GCP)]
* xref:/appliance/vmware/vmware-intro.adoc[VMware]

[#partition-hosts]
== Partition the hosts

Ensure that all ThoughtSpot hosts have the following partitions on the root drive.

Note that the size of the root drive on appliances is limited to 200GB;
the partition requirements are therefore somewhat different when compared to the other environments.+++<table>++++++<tbody>++++++<tr>++++++<th>+++Platform+++</th>+++
+++<th>+++Partition+++</th>+++
+++<th>+++Drive type+++</th>+++
+++<th>+++Description+++</th>+++
+++<th>+++Minimum size+++</th>++++++</tr>+++
+++<tr>++++++<th rowspan="2">+++Hosts in AWS, GCP, and VMWare&nbsp;+++</th>+++
+++<td>+++OS partition+++</td>+++
+++<td>+++SSD (root drive)+++</td>+++
+++<td>+++Root partition for OS, +++<code>+++/tmp+++</code>++++++</td>+++
+++<td>+++100GB+++<br>++++++</br>+++Allocate at least 50GB to +++<code>+++/tmp+++</code>++++++</td>++++++</tr>+++
+++<tr>++++++<td>+++Export partition+++</td>+++
+++<td>+++SSD (root drive)&nbsp;+++</td>+++
+++<td>+++Stores ThoughtSpot objects, hdfs logs, service logs, and so on+++</td>+++
+++<td>+++200GB+++</td>++++++</tr>+++
+++<tr>++++++<th rowspan="2">+++Hosts on ThoughtSpot-certified hardware appliances+++</th>+++
+++<td>+++OS partition+++</td>+++
+++<td>+++SSD (root drive)+++</td>+++
+++<td>+++Root partition for OS, +++<code>+++/tmp+++</code>++++++</td>+++
+++<td>+++80GB+++<br>++++++</br>+++Allocate at least 50GB to +++<code>+++/tmp+++</code>++++++</td>++++++</tr>+++
+++<tr>++++++<td>+++Export partition+++</td>+++
+++<td>+++SSD (root drive)&nbsp;+++</td>+++
+++<td>+++Stores ThoughtSpot objects, hdfs logs, service logs, and so on+++</td>+++
+++<td>+++100GB+++</td>++++++</tr>++++++</tbody>++++++</table>+++

[#install-rhel]
== Install RHEL on hosts

ThoughtSpot is certified with RHEL version 7.7;
we *do not* support other versions of RHEL, including 8 and 8.1.

[#enable-hosts]
== Enable the hosts to download RHEL packages

Make sure that you can download RHEL packages to all hosts, either from the <<official-repositories,official package repositories>>, or from a <<mirror-repositories,mirror repository>> owned and managed by your organization.

If the cluster is offline, and there is no mirror repository in your organization, please contact ThoughtSpot Support.

*Official package repositories*

If the hosts of your ThoughtSpot cluster can access external repositories, either directly or through a proxy, your cluster is online.
You can then proceed to download <<yum-repositories,Yum>>, <<python-repositories,Python>>, and <<r-repositories,R>> package repositories.

*Internal mirror repository*

If the hosts of your ThoughtSpot cluster have access to an internal repository that mirrors the public repositories, copy the <<yum-repositories,Yum>>, <<python-repositories,Python>>, and <<r-repositories,R>> package repositories to your hosts.

*Repositories*

* *Yum repositories*: you must enable the following Yum repositories in your cluster: `epel`, `nux-desktop`, `pgdg95`, `rhel`, `rhel-optional`, `rhel-extras`.

* *Python repository*: for Python, enable the `PyPI` repository.

* *R repository*: for R, enable the `CRAN` repository.

[#enable-ansible]
== Enable an Ansible Control Server

Configure an Ansible Control Server, on a separate host, to run the Ansible playbook that ThoughtSpot supplies.
You must install both `rsync` and Ansible on the Ansible Control Server host.

[#disable-selinux]
== Disable SELinux

We recommend that you disable SELinux if your organization permits it.
