= ThoughtSpot artifacts for RHEL
:last_updated: 3/20/2020
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Get the two primary tarball artifacts for configuring ThoughtSpot using RHEL.

You must have the following artifacts to install or upgrade ThoughtSpot applications that run on RHEL:

* The *Ansible tarball* contains a set of scripts for installing OS packages, dependencies, the ThoughtSpot CLI (tscli), and configuring your cluster (preparing the disks).
Please join our RHEL Early Access program, and email us your mailto:early_access@thoughtspot.com?subject=RHEL%20Early%20Access%20Program%20Ansible%20File%20Request[Ansible request].
* The *Release tarball* contains the ThoughtSpot software binaries (`tar.gz`) of the release version you are installing or upgrading;
for example, ThoughtSpot Release 6.0.4.
You can obtain this file from the https://thoughtspot.egnyte.com/[ThoughtSpot secure file sharing system].
We sent this information to you in our Welcome email.
Contact ThoughtSpot Support if you experience difficulties accessing these files.
