= Español (latín) Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc[< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/es-US/keywords-general-es-US.adoc %}

== Date

{% include content/keywords-translate/es-US/keywords-date-es-US.adoc %}

== Time

{% include content/keywords-translate/es-US/keywords-time-es-US.adoc %}

== Text

{% include content/keywords-translate/es-US/keywords-text-es-US.adoc %}

== Number

{% include content/keywords-translate/es-US/keywords-number-es-US.adoc %}

== Comparative

{% include content/keywords-translate/es-US/keywords-comparative-es-US.adoc %}

== Location

{% include content/keywords-translate/es-US/keywords-location-es-US.adoc %}

== Period

{% include content/keywords-translate/es-US/keywords-period-es-US.adoc %}
