= Português (Brasil) Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/pt-BR/keywords-general-pt-BR.adoc %}

== Date

{% include content/keywords-translate/pt-BR/keywords-date-pt-BR.adoc %}

== Time

{% include content/keywords-translate/pt-BR/keywords-time-pt-BR.adoc %}

== Text

{% include content/keywords-translate/pt-BR/keywords-text-pt-BR.adoc %}

== Number

{% include content/keywords-translate/pt-BR/keywords-number-pt-BR.adoc %}

== Comparative

{% include content/keywords-translate/pt-BR/keywords-comparative-pt-BR.adoc %}

== Location

{% include content/keywords-translate/pt-BR/keywords-location-pt-BR.adoc %}

== Period

{% include content/keywords-translate/pt-BR/keywords-period-pt-BR.adoc %}
