= Dansk Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc[< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/da-DK/keywords-general-da-DK.adoc %}

== Date

{% include content/keywords-translate/da-DK/keywords-date-da-DK.adoc %}

== Time

{% include content/keywords-translate/da-DK/keywords-time-da-DK.adoc %}

== Text

{% include content/keywords-translate/da-DK/keywords-text-da-DK.adoc %}

== Number

{% include content/keywords-translate/da-DK/keywords-number-da-DK.adoc %}

== Comparative

{% include content/keywords-translate/da-DK/keywords-comparative-da-DK.adoc %}

== Location

{% include content/keywords-translate/da-DK/keywords-location-da-DK.adoc %}

== Period

{% include content/keywords-translate/da-DK/keywords-period-da-DK.adoc %}

////
## Help

{% include content/keywords-translate/da-DK/keywords-help-da-DK.adoc %}
////
