= Deutsche Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc[< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/DE/keywords-general-de-DE.adoc %}

== Date

{% include content/keywords-translate/DE/keywords-date-de-DE.adoc %}

== Time

{% include content/keywords-translate/DE/keywords-time-de-DE.adoc %}

== Text

{% include content/keywords-translate/DE/keywords-text-de-DE.adoc %}

== Number

{% include content/keywords-translate/DE/keywords-number-de-DE.adoc %}

== Comparative

{% include content/keywords-translate/DE/keywords-comparative-de-DE.adoc %}

== Location

{% include content/keywords-translate/DE/keywords-location-de-DE.adoc %}

== Period

{% include content/keywords-translate/DE/keywords-period-de-DE.adoc %}

////
## Help

{% include content/keywords-translate/DE/keywords-help-de-DE.adoc %}
////
