= Norsk Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc[< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/nb-NO/keywords-general-nb-NO.adoc %}

== Date

{% include content/keywords-translate/nb-NO/keywords-date-nb-NO.adoc %}

== Time

{% include content/keywords-translate/nb-NO/keywords-time-nb-NO.adoc %}

== Text

{% include content/keywords-translate/nb-NO/keywords-text-nb-NO.adoc %}

== Number

{% include content/keywords-translate/nb-NO/keywords-number-nb-NO.adoc %}

== Comparative

{% include content/keywords-translate/nb-NO/keywords-comparative-nb-NO.adoc %}

== Location

{% include content/keywords-translate/nb-NO/keywords-location-nb-NO.adoc %}

== Period

{% include content/keywords-translate/nb-NO/keywords-period-nb-NO.adoc %}

////
## Help

{% include content/keywords-translate/nb-NO/keywords-help-nb-NO.adoc %}
////
