= Français (Canada) Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc[< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/fr-CA/keywords-general-fr-CA.adoc %}

== Date

{% include content/keywords-translate/fr-CA/keywords-date-fr-CA.adoc %}

== Time

{% include content/keywords-translate/fr-CA/keywords-time-fr-CA.adoc %}

== Text

{% include content/keywords-translate/fr-CA/keywords-text-fr-CA.adoc %}

== Number

{% include content/keywords-translate/fr-CA/keywords-number-fr-CA.adoc %}

== Comparative

{% include content/keywords-translate/fr-CA/keywords-comparative-fr-CA.adoc %}

== Location

{% include content/keywords-translate/fr-CA/keywords-location-fr-CA.adoc %}

== Period

{% include content/keywords-translate/fr-CA/keywords-period-fr-CA.adoc %}
