= Working with charts
:last_updated: 2/25/2020
:permalink: /:collection/:path.html
:page-partial:
:summary: Charts display your search answer in a visual way.

Your search needs at least link:about-attributes-and-measures.adoc[one attribute and one measure] to be presented as a chart.
When you choose to display your answer as a chart, ThoughtSpot will assign it the best fit chart type.

NOTE: Colors are maintained across searches within a session.
why?! For example, when doing a search on revenue by state, each state will keep its color assigned to it even if you change the search or chart type.

* *xref:chart-types.adoc[Chart types]*
+You can choose from a large number of chart types in ThoughtSpot. Each chart type provides you with a different visualization for your answer.

* *xref:chart-configure.adoc[Changing charts]*
+
+++ <span class="badge badge-danger">Danger</span>+++ You can change colors, set gridlines, reorder lables, adjust the axes, change number formatting, and configure other options on your charts.
+++
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary">Left</button>
  <button type="button" class="btn btn-secondary">Middle</button>
  <button type="button" class="btn btn-secondary">Right</button>
</div>
+++
+++
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
  </ul>
+++
