= Overview
:last_updated: 1/13/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: You can install ThoughtSpot on a cloud provider, VMware, or on a hardware appliance.

You can install a ThoughtSpot cluster on a hardware appliance, cloud service, or VMware appliance.
All ThoughtSpot nodes need to be on the same platform and same subnet with no connectivity blocked between any two nodes.
You can have multiple clusters on multiple platforms, but you cannot host one cluster on multiple platforms.

This guide instructs you on how to prepare each of the following:

* xref:/appliance/hardware/inthebox.adoc[Hardware appliance]
* xref:/appliance/aws/configuration-options.adoc[Amazon Web Services (AWS) EC2]
* xref:/appliance/azure/configuration-options.adoc[Microsoft Azure]
* xref:/appliance/gcp/configuration-options.adoc[Google Cloud Platform (GCP)]
* xref:/appliance/vmware/vmware-intro.adoc[VMware]

After you configure your nodes, you can contact xref:/appliance/contact.adoc[ThoughtSpot Support] by phone, mail, email, or by filing a support ticket.
