= About installation and upgrades
:last_updated: 3/4/2020
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: As administrator, you are responsible for setting up and configuring ThoughtSpot. This guide explains how. It will also assist you in troubleshooting some common problems, finding additional resources, and contacting ThoughtSpot.

Your ThoughtSpot application software is already installed for you in a ThoughtSpot appliance.
This is true for both physical and virtual appliances.

The ThoughtSpot software is updated by ThoughtSpot Support.
ThoughtSpot Support will contact you to schedule an update when one becomes available.

As administrator, you are responsible for setting up and configuring ThoughtSpot.
This guide explains how.
It will also assist you in troubleshooting some common problems, finding additional resources, and contacting ThoughtSpot.

[#display-current-config]
== Display your current configuration

To perform the setup and configuration, you must first learn how to link:{{ site.baseurl }}/admin/setup/logins.html[gain administrative access].

. Log in to the ThoughtSpot cluster as the `admin` user.
. Use the `tscli feature` subcommand to display your current configuration.
+
----
 $ tscli feature get-all-config
 +---------------------------------+----------+---------------+
 |              NAME               |  STATUS  | CONFIGURATION |
 +---------------------------------+----------+---------------+
 | Firewall                        | Disabled |               |
 | Saml                            | Disabled |               |
 | Ldap                            | Disabled |               |
 | CustomBranding                  | Disabled |               |
 | CustomBrandingFontCustomization | Disabled |               |
 | DataConnect                     | Disabled |               |
 | RLS                             | Enabled  |               |
 | Callhome                        | Enabled  |               |
 | SSHTunnel                       | Enabled  |               |
 | Fileserver                      | Disabled |               |
 +---------------------------------+----------+---------------+
----

[#related]
== Related information

The following tasks are also available:

* link:{{ site.baseurl }}/admin/setup/set-your-thoughtspot-locale.html[Set your locale]
* link:{{ site.baseurl }}/admin/setup/test-network.html[Test connectivity between nodes]
* link:{{ site.baseurl }}/admin/setup/set-custom-calendar.html[Set up a fiscal calendar year]
* link:{{ site.baseurl }}/admin/setup/about-LDAP.html[Integrate LDAP]
* link:{{ site.baseurl }}/admin/setup/set-up-monitoring.html[Set up monitoring]
* link:{{ site.baseurl }}/admin/setup/work-with-ts-support.html[Configure support services]
* link:{{ site.baseurl }}/admin/setup/firewall-ports.html[Network ports]
* link:{{ site.baseurl }}/admin/setup/about-load-balancer-configuration.html[Configure load balancing and proxies]
* link:{{ site.baseurl }}/admin/setup/customize-style.html[Customize look and feel]
* link:{{ site.baseurl }}/admin/setup/slack-integration.html[Add the Slack integration]
