= Nederland Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc[< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/nl-NL/keywords-general-nl-NL.adoc %}

== Date

{% include content/keywords-translate/nl-NL/keywords-date-nl-NL.adoc %}

== Time

{% include content/keywords-translate/nl-NL/keywords-time-nl-NL.adoc %}

== Text

{% include content/keywords-translate/nl-NL/keywords-text-nl-NL.adoc %}

== Number

{% include content/keywords-translate/nl-NL/keywords-number-nl-NL.adoc %}

== Comparative

{% include content/keywords-translate/nl-NL/keywords-comparative-nl-NL.adoc %}

== Location

{% include content/keywords-translate/nl-NL/keywords-location-nl-NL.adoc %}

== Period

{% include content/keywords-translate/nl-NL/keywords-period-nl-NL.adoc %}

////
## Help

{% include content/keywords-translate/nl-NL/keywords-help-nl-NL.adoc %}
////
