= Suomi Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc[< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/fi-FI/keywords-general-fi-FI.adoc %}

== Date

{% include content/keywords-translate/fi-FI/keywords-date-fi-FI.adoc %}

== Time

{% include content/keywords-translate/fi-FI/keywords-time-fi-FI.adoc %}

== Text

{% include content/keywords-translate/fi-FI/keywords-text-fi-FI.adoc %}

== Number

{% include content/keywords-translate/fi-FI/keywords-number-fi-FI.adoc %}

== Comparative

{% include content/keywords-translate/fi-FI/keywords-comparative-fi-FI.adoc %}

== Location

{% include content/keywords-translate/fi-FI/keywords-location-fi-FI.adoc %}

== Period

{% include content/keywords-translate/fi-FI/keywords-period-fi-FI.adoc %}

////
## Help

{% include content/keywords-translate/fi-FI/keywords-help-fi-FI.adoc %}
////
