= Español (España) Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc[< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/es-ES/keywords-general-es-ES.adoc %}

== Date

{% include content/keywords-translate/es-ES/keywords-date-es-ES.adoc %}

== Time

{% include content/keywords-translate/es-ES/keywords-time-es-ES.adoc %}

== Text

{% include content/keywords-translate/es-ES/keywords-text-es-ES.adoc %}

== Number

{% include content/keywords-translate/es-ES/keywords-number-es-ES.adoc %}

== Comparative

{% include content/keywords-translate/es-ES/keywords-comparative-es-ES.adoc %}

== Location

{% include content/keywords-translate/es-ES/keywords-location-es-ES.adoc %}

== Period

{% include content/keywords-translate/es-ES/keywords-period-es-ES.adoc %}

////
## Help

{% include content/keywords-translate/es-ES/keywords-help-es-ES.adoc %}
////
