= Svenska Keyword reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.
You can also see this list of keywords and examples from within the help center.

|===
| xref:/reference/keywords.adoc[< Back to English Keywords page]
|===

== General

{% include content/keywords-translate/sv-SE/keywords-general-sv-SE.adoc %}

== Date

{% include content/keywords-translate/sv-SE/keywords-date-sv-SE.adoc %}

== Time

{% include content/keywords-translate/sv-SE/keywords-time-sv-SE.adoc %}

== Text

{% include content/keywords-translate/sv-SE/keywords-text-sv-SE.adoc %}

== Number

{% include content/keywords-translate/sv-SE/keywords-number-sv-SE.adoc %}

== Comparative

{% include content/keywords-translate/sv-SE/keywords-comparative-sv-SE.adoc %}

== Location

{% include content/keywords-translate/sv-SE/keywords-location-sv-SE.adoc %}

== Period

{% include content/keywords-translate/sv-SE/keywords-period-sv-SE.adoc %}

////
## Help

{% include content/keywords-translate/sv-SE/keywords-help-sv-SE.adoc %}
////
