= 6.1 Release Notes
:last_updated: 04/09/2020
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar

ThoughtSpot version 6.1 is now available.
These release notes include information about new and enhanced features.

For a complete list of issues that we fixed in this release, see xref:/release/fixed.adoc[Fixed issues].

* <<6-1-new,6.1 New Features>>
* <<early-access,Early Access Programs>>
* <<beta-program,Beta Programs>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#6-1-new]
== 6.1 New Features and Functionality

For a complete list of issues that we fixed in this release, see xref:/release/fixed.adoc#6-1[6.1 Fixed issues].

=== Updating ThoughtSpot UI through CDN

Starting with this release, you can configure automatic updates of the front end of the ThoughtSpot application by uploading from CDN (Amazon Cloudfront).
This enables your organization to get many new features of ThoughtSpot and get many critical bug fixes without experiencing the traditional upgrade downtime.

UI auto-update is in the Early Access phase.
Please contact us if you are interested in participating in the link:mailto:early_access@thoughtspot.com?subject=UI%20Update%20Early%20Access%20Program%20Request[UI Update Early Access Program].

=== Back up and restore ThoughtSpot AWS and GCP clusters using cloud storage

With AWS, you can back up and restore using an S3 bucket.
With GCP, you can back up and restore using a GCS bucket.

For details, see:

* xref:/appliance/aws/aws-backup-restore.adoc[Back up and restore an AWS cluster using S3]
* xref:/appliance/gcp/gcp-backup-restore.adoc[Back up and restore a GCP cluster using GCS]

=== Geo map support for Norway and Switzerland

For details, see: xref:/reference/geomap-reference.adoc[Geo Map reference]

=== New SQL commands for ODBC and JDBC drivers

For developers creating tools to connect to ThoughtSpot through the ODBC or JDBC driver, the following new commands are available:

* `ALTER TABLE`
* `CREATE DATABASE`
* `CREATE SCHEMA`
* `DROP`
* `SCRIPT`
* `SHOW`
* `TRUNCATE`

For details, see: xref:/data-integrate/reference/odbc-commands.adoc[Supported SQL commands].

=== Upgrade to Python 3

Starting with this release, ThoughtSpot uses Python 3 packages.
For example, to invoke the `syncUsersAndGroups.py` script the script, you must now use the `python3` command;
see xref:/admin/setup/sync-users-and-groups-from-ldap.adoc[Sync users and groups from LDAP].

[#early-access]
== Early Access Programs

=== UI update

Please contact us if you are interested in participating in the link:mailto:early_access@thoughtspot.com?subject=UI%20Update%20Early%20Access%20Program%20Request[UI Update Early Access Program].

=== RHEL support

RHEL support is in the Early Access phase.
To deploy ThoughtSpot on RHEL, you must have the Ansible tarball;
please contact us if you are interested in participating in the link:mailto:early_access@thoughtspot.com?subject=RHEL%20Early%20Access%20Program%20Request[RHEL Early Access Program].
For more information, see xref:/appliance/rhel/rhel.adoc[RHEL Deployment Overview].

[#beta-program]
== Beta Programs

If you are interested in seeing some of our newest features, we want to add you to our testing group.
ThoughtSpot is looking for people with all levels of experience: end-users, analysts, administrators, configurators, and so on.
We like to have a diversity of experience and perspective, and want to hear from you.
Because we strive for excellence, we will partner with you to adjust the final details of our offerings based on your feedback.

=== Monitor

Please contact us if you are interested in participating in the link:mailto:BetaProgram@thoughtspot.com?subject=Monitor%20Beta%20Program%20Request[Monitor Beta Program], for monitoring selected metrics over time.

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 6.1 release directly:

* 5.3.x to 6.1
* 6.0.x to 6.1

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.
First, upgrade to version 5.2.x, or version 5.3.x, and then to the 6.1 release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address.
Without valid email addresses, the upgrade is blocked.
